FROM hardikparwana/cuda116desktop:ipopt
RUN apt-get update
RUN apt install -y python3-pip
RUN apt install -y vim tmux
#RUN sudo apt-get install gcc g++ gfortran git patch wget pkg-config liblapack-dev libmetis-dev

